version: "3.7"
services:
  web:
    image: node
    volumes:
      - ./server:/src
    working_dir: /src
    command: npm run develop
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=$DB_USER
      - DATABASE_PASSWORD=$DB_PASSWORD
    ports:
      - "1337:1337"
  db:
    image: mongo
    volumes:
      - ./mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
