version: "3.7"
services:
  web:
    image: node
    volumes:
      - ./server:/src
    working_dir: /src
    # env_file: server.env
  db:
    image: mongo
    volumes:
      - ./mongo-db:/data/db
    # env_file: db.env
